name: "bindgen"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_SDK_VERSION: 6.0.x

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

jobs:

  bindgen-job:
    name: "Bindgen"
    runs-on: ubuntu-latest
    steps:

    - name: "Clone Git repository"
      uses: actions/checkout@master
      with:
        submodules: true

    - name: "Bindgen"
      shell: bash
      run: ./bindgen.sh

    - name: "Add + commit + push (if necessary)"
      uses: EndBug/add-and-commit@v7
      with:
        default_author: user_info
        message: "Update bindings"

