name: "Build"
permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:

  build-native-library-job:
    name: "Build SDL3: ${{ matrix.platform.rid }}"
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows (x64), os: windows-2025, rid: win-x64 }
          - { name: Windows (arm64), os: windows-2025, rid: win-arm64 }
          - { name: macOS (x64), os: macos-latest, rid: osx-x64 }
          - { name: macOS (arm64), os: macos-latest, rid: osx-arm64 }
          - { name: Linux (x64), os: ubuntu-latest, rid: linux-x64 }
          # Disabled building for `linux-arm64` until GitHub Actions runner images are generally available. See: https://github.com/orgs/community/discussions/19197
          # - { name: Linux (arm64), os: ubuntu-latest, rid: linux-arm64 }
    steps:

      - name: "Clone Git repository"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: "Cache"
        id: cache-libs
        uses: actions/cache@v3
        with:
          path: "./lib"
          key: "native-library-SDL3_${{ matrix.platform.rid }}_${{ hashFiles('ext/SDL/**/*') }}"

      # https://wiki.libsdl.org/SDL3/README/linux#build-dependencies
      - name: "Install dependencies linux-x64"
        if: matrix.platform.rid == 'linux-x64' && steps.cache-libs.outputs.cache-hit != 'true'
        run: sudo apt-get install build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      # Disabled building for `linux-arm64` until GitHub Actions runner images are generally available. See: https://github.com/orgs/community/discussions/19197
      # - name: "Build native library: linux-arm64 dependencies"
      #   if: matrix.platform.rid == 'linux-arm64' && steps.cache-libs.outputs.cache-hit != 'true'
      #   run: sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: "Build"
        if: steps.cache-libs.outputs.cache-hit != 'true'
        shell: bash
        run: ./ext/build-native-library.sh release ${{ matrix.platform.rid }}

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: "native-library-SDL3-${{ matrix.platform.rid }}"
          path: "./lib"
          if-no-files-found: error

  build-dotnet-job:
    name: "Build .NET solution"
    needs: [build-native-library-job]
    runs-on: ubuntu-latest
    steps:

      - name: "Clone Git repository"
        uses: actions/checkout@master

      - name: "Download native library SDL3 (win-x64)"
        uses: actions/download-artifact@v4
        with:
          name: "native-library-SDL3-win-x64"
          path: "./lib"

      - name: "Download native library SDL (osx-x64)"
        uses: actions/download-artifact@v4
        with:
          name: "native-library-SDL3-osx-x64"
          path: "./lib"

      - name: "Download native library SDL (osx-arm64)"
        uses: actions/download-artifact@v4
        with:
          name: "native-library-SDL3-osx-arm64"
          path: "./lib"

      - name: "Download native library SDL (linux-x64)"
        uses: actions/download-artifact@v4
        with:
          name: "native-library-SDL3-linux-x64"
          path: "./lib"

      # Disabled building for `linux-arm64` until GitHub Actions runner images are generally available. See: https://github.com/orgs/community/discussions/19197
      # - name: "Download native library (linux-arm64)"
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: "native-library-SDL3-linux-arm64"
      #     path: "./lib"

      - name: "Download generated C# code"
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: "generated-cs"
          path: "./src/cs/production/Interop.SDL/Generated"

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: "Build .NET solution"
        run: dotnet build "./src/cs"

      - name: "Upload generated C# code with source generators"
        uses: actions/upload-artifact@v4
        with:
          name: "generated-cs-with-source-generators"
          path: "./src/cs/production/Interop.SDL/Generated"
          if-no-files-found: error
