name: "Commit Generated Code"
permissions:
  contents: read

on:
  workflow_call:

jobs:

  commit-job:
    name: "Commit generated C# code"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: 'true'

      - name: "Download changes to commit"
        uses: actions/download-artifact@v4
        with:
          name: "generated-cs"
          path: "./src/cs/production/Interop.SDL/Generated"

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          author_name: 'lithiumtoast'
          author_email: '519592+lithiumtoast@users.noreply.github.com'
          committer_name: '${{ github.actor_id }}'
          committer_email: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          message: "Update C# bindings"
