name: "Commit Generated Code"

on:
  workflow_call:

jobs:

  commit-job:
    name: "Commit generated C# code"
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions: write-all

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: 'true'

      - name: "Download changes to commit"
        uses: actions/download-artifact@v4
        with:
          name: "generated-cs"
          path: "./src/cs/production/Interop.SDL/Generated"

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'lithiumtoast'
          author_email: '519592+lithiumtoast@users.noreply.github.com'
          committer_name: 'dependabot[bot]'
          committer_email: '49699333+dependabot[bot]@users.noreply.github.com'
          message: "Update C# bindings"
