name: "Pull Request"
permissions:
  contents: read

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - '**.md'

jobs:

  dependabot-metadata-job:
    name: "Dependabot metadata"
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: "Dependabot get metadata"
        id: "dependabot-metadata"
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0

      - name: "Dependabot print metadata"
        shell: bash
        run: |
          echo "$GITHUB_REPOSITORY \n"
          echo "$PR_URL \n"
          echo "$DEPENDENCY_NAMES \n"
          echo "$DEPENDENCY_TYPE \n"
          echo "$PREVIOUS_VERSION \n"
          echo "$NEW_VERSION \n"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          DEPENDENCY_NAMES: ${{ steps.dependabot-metadata.outputs.dependency-names }}
          DEPENDENCY_TYPE: ${{ steps.dependabot-metadata.outputs.dependency-type }}
          UPDATE_TYPE: ${{ steps.dependabot-metadata.outputs.update-type }}
          UPDATED_DEPENDENCIES_JSON: ${{ steps.dependabot-metadata.outputs.updated-dependencies-json }}
          PREVIOUS_VERSION: ${{ steps.dependabot-metadata.outputs.previous-version }}
          NEW_VERSION: ${{ steps.dependabot-metadata.outputs.new-version }}

  dependabot-bindgen-job:
    name: "Dependabot Bindgen"
    needs: [dependabot-metadata-job]
    uses: "./.github/workflows/bindgen.yml"

  dependabot-commit-job:
    name: "Dependabot Commit"
    needs: [dependabot-bindgen-job]
    permissions:
      contents: write
    uses: "./.github/workflows/commit.yml"

  not-dependabot-build-job:
    name: "Build"
    uses: "./.github/workflows/build.yml"
    if: github.event.pull_request.user.login != 'dependabot[bot]'
